script: "echo # FIXME: depends on rnv, but not installable from Apt "
#
language: node_js

node_js:
  - "0.12"

addons:
  apt:
    packages: []
#       - rnv

env:
  global: []
  matrix:
  - NODE_ENV=
#  - NODE_ENV=testing
#  - NODE_ENV=production

branches:
  only:
  - master
  - /^v[0-9]+.[0-9]+.[0-9]+$

